### ISSUE TITLE
Rutherford Scattering master checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/rutherford-scattering#15]
## Design
- [x] **Design doc created** (Date: 02/15/2015) 
  - [x] Make phethelp@gmail.com owner, share with phet-team
  - [x] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date:02/18/2015)
- [x] **Design concept complete**  (Date: 02/04/2016)
- [x] **Wireframes complete** (Date: 02/14/2016) 
- [x] **Mockups complete** (Date: 07 /15/2016) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 06/24/2016) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date:08/05/2016) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Compatible activities ([author spreadsheet](https://docs.google.com/spreadsheets/d/1AOc1vy0HfEeJQ9sT0Vs_sr6dqmsEHfq7HWUBGQV_VQA/edit#gid=0))
  - [x] Update [Gooru spreadsheet](https://docs.google.com/spreadsheets/d/13qvc7e71zTTjaJ2VcYhhU0rNxvH4kYFnoScVCOvvf7U/edit#gid=1717560774)
  - [x] Sim primer
  - [x] Verify credits
- [x] **Add to Edmodo**
## Implementation
- [x] **Sim repo created** (Date: 02/11/2015) 
  - [x] Collaborators added (such as QA team, designers, etc) 
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo
- [x] **Initial development started** (Date: 02/03/2016)
- [x] **Sim feature complete** (Date: 3/1/2016) 
- [x] **Code review complete** (Date: 3/8/2016) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 08/17/2016)
  - [x] Update repo README to published template
## QA
- [x] Legacy sim tested for bugs, issues reported in repo
- [x] **Dev testing complete** (Date: 08/03/2016) 
- [x] **First release candidate** (Date: 08/05/2016)
  - [x] phethelp@gmail.com owner of test matrix, share with phet-team, add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
  - [x] Test matrix deemed complete

**Comment by ariel-phet** [comment]
@amyh-phet can you check off any of these you were responsible for? (and perhaps put in a date for lead designer sign off, I would assume this is after the projector mode request)

**Comment by amyh-phet** [comment]
@ariel-phet    Checked off a few items.  I'm working on getting activities transferred over today.  Let me know if I need to do anything for Gooru or Edmodo.   Primer will happen soon.

**Comment by ariel-phet** [comment]
@amyh-phet final items are for you, removing my assignment

**Comment by amyh-phet** [comment]
Primer uploaded.
